from enum import Enum


class Site:
    DRAFTKINGS = 'DRAFTKINGS'
    FANDUEL = 'FANDUEL'
    YAHOO = 'YAHOO'
    FANTASY_DRAFT = 'FANTASY_DRAFT'
    FANBALL = 'FANBALL'
    DRAFTKINGS_CAPTAIN_MODE = 'DRAFTKINGS_CAPTAIN_MODE'
    FANDUEL_SINGLE_GAME = 'FANDUEL_SINGLE_GAME'
    DRAFTKINGS_TIERS = 'DRAFTKINGS_TIERS'


class Sport:
    FOOTBALLNCAA = 'FOOTBALLNCAA'
    FOOTBALL = 'FOOTBALL'

